[package]
name = "rata1"
version = "0.1.1"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
ratatui = { version = "0.29.0", features = ["all-widgets"] }
material = { version = "0.1.1", features = ["ratatui"] }
rand = "0.9.1"
rodio = "0.20.1"
